[workspace]
authors = ["adiezsanchez <adiez.biotech@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "brain_nuc_stardist"
version = "0.1.0"
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
test = "python tests/test_pipeline.py"

[dependencies]
apoc-backend = "*"
csbdeep = "==0.8.1"
czifile = "*"
edt = "*"
ipykernel = "*"
ipython = "*"
napari = "*"
nbformat = "*"
nd2 = "*"
plotly = "*"
pyclesperanto-prototype = "*"
pyqt = "*"
python = "3.10"
stardist = "==0.8.5"

# Pinned versions for reproducibility
numba = "==0.59.1"
numpy = "==1.26.4"
reikna = "==0.8.0"
gputools = "==0.2.15"

# -------------------------
# Platform-specific deps
# -------------------------

[target.win-64.dependencies]
cudatoolkit = "11.2"
cudnn = "8.1.0"

[target.linux-64.dependencies]
cudatoolkit = "11.2"
cudnn = "8.1.0"

# macOS: no CUDA, use CPU TF by default
[target.osx-64.dependencies]
# nothing extra here

# -------------------------
# PyPI deps
# -------------------------

[pypi-dependencies]
# Default: works on Linux/Win and CPU macOS
tensorflow = "==2.10.1"

[target.osx-64.pypi-dependencies]
# Prefer Apple builds if available
tensorflow-macos = "*"
tensorflow-metal = "*"
