[workspace]
authors = ["adiezsanchez <adiez.biotech@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "brain_nuc_stardist"
version = "0.1.0"
platforms = ["linux-64", "win-64"]  # removed osx-arm64

[tasks]
lab = "jupyter lab"
test = "python -m tests.test_pipeline"

[dependencies]
apoc-backend = "*"
csbdeep = "==0.8.1"
czifile = "*"
edt = "*"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
napari = "*"
nbformat = "*"
nd2 = "*"
plotly = "*"
pyclesperanto-prototype = "*"
pyqt = "*"
python = "==3.10"
stardist = "==0.8.5"

# pinned for reproducibility
numba = "==0.59.1"
numpy = "==1.26.4"
reikna = "==0.8.0"

# -------------------------
# Platform-specific deps
# -------------------------

[target.win-64.dependencies]
cudatoolkit = "==11.2"
cudnn = "8.1.*"

[target.linux-64.dependencies]
cudatoolkit = "==11.8"       # newer CUDA
cudnn = "8.9.*"              # newer cuDNN

# -------------------------
# PyPI deps
# -------------------------

[target.win-64.pypi-dependencies]
tensorflow = "==2.10.1"      # compatible with CUDA 11.2

[target.linux-64.pypi-dependencies]
tensorflow = "==2.18.0"      # compatible with CUDA 12.1


